// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/Naist4869/awesomeProject1/ent/runtime.go

const (
	Version = "v0.7.1-0.20210321192705-6e3c3b696050"            // Version of ent codegen.
	Sum     = "h1:QXEbHR3vOKqLTXlYWqurfFvSEbLs+PemidE5NEmpnT0=" // Sum of ent codegen.
)
