// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IssueX1355sColumns holds the columns for the "issue_x1355s" table.
	IssueX1355sColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "time", Type: field.TypeTime, Nullable: true},
		{Name: "int32", Type: field.TypeInt32, Nullable: true},
		{Name: "str", Type: field.TypeString, Default: "abc"},
	}
	// IssueX1355sTable holds the schema information for the "issue_x1355s" table.
	IssueX1355sTable = &schema.Table{
		Name:        "issue_x1355s",
		Columns:     IssueX1355sColumns,
		PrimaryKey:  []*schema.Column{IssueX1355sColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IssueX1355sTable,
	}
)

func init() {
}
