// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Naist4869/awesomeProject1/ent/issuex1355"
	"github.com/Naist4869/awesomeProject1/ent/predicate"
)

// IssueX1355Query is the builder for querying IssueX1355 entities.
type IssueX1355Query struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.IssueX1355
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IssueX1355Query builder.
func (ix *IssueX1355Query) Where(ps ...predicate.IssueX1355) *IssueX1355Query {
	ix.predicates = append(ix.predicates, ps...)
	return ix
}

// Limit adds a limit step to the query.
func (ix *IssueX1355Query) Limit(limit int) *IssueX1355Query {
	ix.limit = &limit
	return ix
}

// Offset adds an offset step to the query.
func (ix *IssueX1355Query) Offset(offset int) *IssueX1355Query {
	ix.offset = &offset
	return ix
}

// Order adds an order step to the query.
func (ix *IssueX1355Query) Order(o ...OrderFunc) *IssueX1355Query {
	ix.order = append(ix.order, o...)
	return ix
}

// First returns the first IssueX1355 entity from the query.
// Returns a *NotFoundError when no IssueX1355 was found.
func (ix *IssueX1355Query) First(ctx context.Context) (*IssueX1355, error) {
	nodes, err := ix.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{issuex1355.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ix *IssueX1355Query) FirstX(ctx context.Context) *IssueX1355 {
	node, err := ix.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IssueX1355 ID from the query.
// Returns a *NotFoundError when no IssueX1355 ID was found.
func (ix *IssueX1355Query) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ix.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{issuex1355.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ix *IssueX1355Query) FirstIDX(ctx context.Context) int {
	id, err := ix.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IssueX1355 entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one IssueX1355 entity is not found.
// Returns a *NotFoundError when no IssueX1355 entities are found.
func (ix *IssueX1355Query) Only(ctx context.Context) (*IssueX1355, error) {
	nodes, err := ix.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{issuex1355.Label}
	default:
		return nil, &NotSingularError{issuex1355.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ix *IssueX1355Query) OnlyX(ctx context.Context) *IssueX1355 {
	node, err := ix.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IssueX1355 ID in the query.
// Returns a *NotSingularError when exactly one IssueX1355 ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ix *IssueX1355Query) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ix.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = &NotSingularError{issuex1355.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ix *IssueX1355Query) OnlyIDX(ctx context.Context) int {
	id, err := ix.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IssueX1355s.
func (ix *IssueX1355Query) All(ctx context.Context) ([]*IssueX1355, error) {
	if err := ix.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ix.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ix *IssueX1355Query) AllX(ctx context.Context) []*IssueX1355 {
	nodes, err := ix.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IssueX1355 IDs.
func (ix *IssueX1355Query) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ix.Select(issuex1355.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ix *IssueX1355Query) IDsX(ctx context.Context) []int {
	ids, err := ix.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ix *IssueX1355Query) Count(ctx context.Context) (int, error) {
	if err := ix.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ix.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ix *IssueX1355Query) CountX(ctx context.Context) int {
	count, err := ix.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ix *IssueX1355Query) Exist(ctx context.Context) (bool, error) {
	if err := ix.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ix.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ix *IssueX1355Query) ExistX(ctx context.Context) bool {
	exist, err := ix.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IssueX1355Query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ix *IssueX1355Query) Clone() *IssueX1355Query {
	if ix == nil {
		return nil
	}
	return &IssueX1355Query{
		config:     ix.config,
		limit:      ix.limit,
		offset:     ix.offset,
		order:      append([]OrderFunc{}, ix.order...),
		predicates: append([]predicate.IssueX1355{}, ix.predicates...),
		// clone intermediate query.
		sql:  ix.sql.Clone(),
		path: ix.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Time time.Time `json:"time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IssueX1355.Query().
//		GroupBy(issuex1355.FieldTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ix *IssueX1355Query) GroupBy(field string, fields ...string) *IssueX1355GroupBy {
	group := &IssueX1355GroupBy{config: ix.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ix.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ix.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Time time.Time `json:"time,omitempty"`
//	}
//
//	client.IssueX1355.Query().
//		Select(issuex1355.FieldTime).
//		Scan(ctx, &v)
//
func (ix *IssueX1355Query) Select(field string, fields ...string) *IssueX1355Select {
	ix.fields = append([]string{field}, fields...)
	return &IssueX1355Select{IssueX1355Query: ix}
}

func (ix *IssueX1355Query) prepareQuery(ctx context.Context) error {
	for _, f := range ix.fields {
		if !issuex1355.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ix.path != nil {
		prev, err := ix.path(ctx)
		if err != nil {
			return err
		}
		ix.sql = prev
	}
	return nil
}

func (ix *IssueX1355Query) sqlAll(ctx context.Context) ([]*IssueX1355, error) {
	var (
		nodes = []*IssueX1355{}
		_spec = ix.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &IssueX1355{config: ix.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ix.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ix *IssueX1355Query) sqlCount(ctx context.Context) (int, error) {
	_spec := ix.querySpec()
	return sqlgraph.CountNodes(ctx, ix.driver, _spec)
}

func (ix *IssueX1355Query) sqlExist(ctx context.Context) (bool, error) {
	n, err := ix.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ix *IssueX1355Query) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   issuex1355.Table,
			Columns: issuex1355.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: issuex1355.FieldID,
			},
		},
		From:   ix.sql,
		Unique: true,
	}
	if fields := ix.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuex1355.FieldID)
		for i := range fields {
			if fields[i] != issuex1355.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ix.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ix.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ix.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ix.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, issuex1355.ValidColumn)
			}
		}
	}
	return _spec
}

func (ix *IssueX1355Query) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ix.driver.Dialect())
	t1 := builder.Table(issuex1355.Table)
	selector := builder.Select(t1.Columns(issuex1355.Columns...)...).From(t1)
	if ix.sql != nil {
		selector = ix.sql
		selector.Select(selector.Columns(issuex1355.Columns...)...)
	}
	for _, p := range ix.predicates {
		p(selector)
	}
	for _, p := range ix.order {
		p(selector, issuex1355.ValidColumn)
	}
	if offset := ix.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ix.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IssueX1355GroupBy is the group-by builder for IssueX1355 entities.
type IssueX1355GroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ixb *IssueX1355GroupBy) Aggregate(fns ...AggregateFunc) *IssueX1355GroupBy {
	ixb.fns = append(ixb.fns, fns...)
	return ixb
}

// Scan applies the group-by query and scans the result into the given value.
func (ixb *IssueX1355GroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ixb.path(ctx)
	if err != nil {
		return err
	}
	ixb.sql = query
	return ixb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ixb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ixb.fields) > 1 {
		return nil, errors.New("ent: IssueX1355GroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ixb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) StringsX(ctx context.Context) []string {
	v, err := ixb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ixb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355GroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) StringX(ctx context.Context) string {
	v, err := ixb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ixb.fields) > 1 {
		return nil, errors.New("ent: IssueX1355GroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ixb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) IntsX(ctx context.Context) []int {
	v, err := ixb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ixb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355GroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) IntX(ctx context.Context) int {
	v, err := ixb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ixb.fields) > 1 {
		return nil, errors.New("ent: IssueX1355GroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ixb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ixb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ixb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355GroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) Float64X(ctx context.Context) float64 {
	v, err := ixb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ixb.fields) > 1 {
		return nil, errors.New("ent: IssueX1355GroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ixb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ixb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ixb *IssueX1355GroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ixb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355GroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ixb *IssueX1355GroupBy) BoolX(ctx context.Context) bool {
	v, err := ixb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ixb *IssueX1355GroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ixb.fields {
		if !issuex1355.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ixb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ixb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ixb *IssueX1355GroupBy) sqlQuery() *sql.Selector {
	selector := ixb.sql
	columns := make([]string, 0, len(ixb.fields)+len(ixb.fns))
	columns = append(columns, ixb.fields...)
	for _, fn := range ixb.fns {
		columns = append(columns, fn(selector, issuex1355.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(ixb.fields...)
}

// IssueX1355Select is the builder for selecting fields of IssueX1355 entities.
type IssueX1355Select struct {
	*IssueX1355Query
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ix *IssueX1355Select) Scan(ctx context.Context, v interface{}) error {
	if err := ix.prepareQuery(ctx); err != nil {
		return err
	}
	ix.sql = ix.IssueX1355Query.sqlQuery(ctx)
	return ix.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ix *IssueX1355Select) ScanX(ctx context.Context, v interface{}) {
	if err := ix.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Strings(ctx context.Context) ([]string, error) {
	if len(ix.fields) > 1 {
		return nil, errors.New("ent: IssueX1355Select.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ix.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ix *IssueX1355Select) StringsX(ctx context.Context) []string {
	v, err := ix.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ix.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355Select.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ix *IssueX1355Select) StringX(ctx context.Context) string {
	v, err := ix.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Ints(ctx context.Context) ([]int, error) {
	if len(ix.fields) > 1 {
		return nil, errors.New("ent: IssueX1355Select.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ix.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ix *IssueX1355Select) IntsX(ctx context.Context) []int {
	v, err := ix.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ix.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355Select.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ix *IssueX1355Select) IntX(ctx context.Context) int {
	v, err := ix.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Float64s(ctx context.Context) ([]float64, error) {
	if len(ix.fields) > 1 {
		return nil, errors.New("ent: IssueX1355Select.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ix.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ix *IssueX1355Select) Float64sX(ctx context.Context) []float64 {
	v, err := ix.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ix.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355Select.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ix *IssueX1355Select) Float64X(ctx context.Context) float64 {
	v, err := ix.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Bools(ctx context.Context) ([]bool, error) {
	if len(ix.fields) > 1 {
		return nil, errors.New("ent: IssueX1355Select.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ix.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ix *IssueX1355Select) BoolsX(ctx context.Context) []bool {
	v, err := ix.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ix *IssueX1355Select) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ix.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuex1355.Label}
	default:
		err = fmt.Errorf("ent: IssueX1355Select.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ix *IssueX1355Select) BoolX(ctx context.Context) bool {
	v, err := ix.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ix *IssueX1355Select) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ix.sqlQuery().Query()
	if err := ix.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ix *IssueX1355Select) sqlQuery() sql.Querier {
	selector := ix.sql
	selector.Select(selector.Columns(ix.fields...)...)
	return selector
}
