// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/Naist4869/awesomeProject1/ent/issuex1355"
	"github.com/Naist4869/awesomeProject1/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	issuex1355Fields := schema.IssueX1355{}.Fields()
	_ = issuex1355Fields
	// issuex1355DescStr is the schema descriptor for str field.
	issuex1355DescStr := issuex1355Fields[2].Descriptor()
	// issuex1355.DefaultStr holds the default value on creation for the str field.
	issuex1355.DefaultStr = issuex1355DescStr.Default.(string)
}
