// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IssueX1355 is the predicate function for issuex1355 builders.
type IssueX1355 func(*sql.Selector)
